apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<aws-acc>:role/cluster-eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::<aws-acc>:user/<username>
      username: <username>
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1",...}}
  creationTimestamp: "2023-11-14T03:46:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2829"
  uid: cb1f7da0-5783-44fa-97c3-b75154007a79
